name: Ruby Gem

on:
  release:
    types: [published]

jobs:
  build:
    name: Build + Test + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true # Caches gems between runs

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Publish to RubyGems
        if: success() # Only runs if tests pass
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build avatax.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
